// ╔══════════════════════════════════════════════════════════════════╗
// ║   THREE-BODY PROBLEM SIMULATOR — script.js                      ║
// ║                                                                  ║
// ║   Physics:  Velocity-Verlet N-body integration                  ║
// ║   Renderer: HTML5 Canvas 2D with world↔screen camera transform  ║
// ║   Author:   Generated by Claude (Anthropic)                     ║
// ╚══════════════════════════════════════════════════════════════════╝

'use strict';

// ─────────────────────────────────────────────────────────────────────
//  SIMULATION CONSTANTS
// ─────────────────────────────────────────────────────────────────────

/**
 * Gravitational constant in simulation units (px³ τ⁻² mass⁻¹).
 *
 * Unit calibration:
 *   v_circ = √(G·M/r) = √(50·100/200) = 5 px/τ
 *   Orbital period T = 2π·r/v ≈ 251 τ  at r = 200 px, M = 100
 */
const G = 50;

/**
 * Softening parameter ε² (px²).
 * Prevents 1/r² singularity. Effective ε = 5 px.
 * The modified force law: a_ij = G·m_j·Δr / (r²+ε²)^(3/2)
 */
const SOFTENING_SQ = 25;

/** Base mass — "1 solar mass" in display = BASE_MASS in sim units. */
const BASE_MASS = 100;

/**
 * Velocity-arrow display scale: VEL_SCALE px of arrow per px/τ.
 * Also used to map drag-tip back to velocity.
 */
const VEL_SCALE = 18;

/**
 * Sim time (τ) → "Earth Days" conversion.
 * Calibrated so one Figure-8 orbit (≈ 253 τ) ≈ 365 Earth days.
 *   1 τ = 365 / 253 ≈ 1.442 days
 */
const DAYS_PER_TAU = 1.442;

/** Trail memory: max path points per body. */
const TRAIL_MAX = 800;

/** Body colours (3 bodies). */
const COLS = ['#FFCC00', '#44AAFF', '#FF6644'];
const NAMES = ['α Alpha', 'β Beta', 'γ Gamma'];

// Speed configs: substeps × dt = effective Δτ per animation frame
const SPEED = {
    slow: { substeps: 10, dt: 0.008 },   //  0.08 τ/frame
    normal: { substeps: 50, dt: 0.008 },   //  0.40 τ/frame
    fast: { substeps: 150, dt: 0.008 },   //  1.20 τ/frame
};

// ─────────────────────────────────────────────────────────────────────
//  PRESET FACTORY FUNCTIONS
// ─────────────────────────────────────────────────────────────────────

/**
 * Chenciner–Montgomery Figure-8 choreography (year 2000).
 *
 * Original: G = 1, m = 1, positions in natural units (≈ ±1).
 * Scaling to our system:
 *   L_scale = 200 px/unit      → positions × 200
 *   T_scale = √(L³/(G·m)) = √(8e6/5000) = 40
 *   V_scale = L/T = 200/40 = 5 → velocities × 5
 */
const P_FIGURE8 = () => ({
    bodies: [
        { x: -0.97000436 * 200, y: 0.24308753 * 200, vx: 0.46620368 * 5, vy: 0.43236573 * 5 },
        { x: 0, y: 0, vx: -0.93240737 * 5, vy: -0.86473146 * 5 },
        { x: 0.97000436 * 200, y: -0.24308753 * 200, vx: 0.46620368 * 5, vy: 0.43236573 * 5 },
    ],
    masses: [BASE_MASS, BASE_MASS, BASE_MASS],
});

/**
 * Lagrange equilateral-triangle choreography.
 *
 * Three equal masses sit at vertices of an equilateral triangle,
 * each orbiting the CoM with the same angular velocity ω.
 *
 * Force balance on one body (side s, circumradius R = s/√3):
 *   Net radial force = √3·G·m²/s²
 *   Centripetal:       m·ω²·R = √3·G·m²/s²
 *   → ω² = 3·G·m / s³
 */
const P_LAGRANGE = () => {
    const s = 240;                      // side length (px)
    const R = s / Math.sqrt(3);         // circumradius
    const m = BASE_MASS;
    const ω = Math.sqrt(3 * G * m / (s * s * s));
    const v = ω * R;
    const bods = [];
    for (let k = 0; k < 3; k++) {
        const θ = -Math.PI / 2 + k * (2 * Math.PI / 3);
        bods.push({
            x: R * Math.cos(θ), y: R * Math.sin(θ),
            vx: -v * Math.sin(θ), vy: v * Math.cos(θ),
        });
    }
    return { bodies: bods, masses: [m, m, m] };
};

/**
 * Binary star + circumbinary planet.
 *
 * Two equal heavy stars orbit their CoM; one lighter planet
 * orbits the pair at a wider radius.
 *
 * Binary angular speed:  ω_b² = G·M_star / (4·d³)
 * Planet circular speed: v_p  = √(G·(2·M_star) / r_p)
 */
const P_BINARY = () => {
    const Mstar = 200, d = 100;
    const ωb = Math.sqrt(G * Mstar / (4 * d * d * d));
    const vb = ωb * d;                        // star orbital speed

    const rp = 380;
    const vp = Math.sqrt(G * 2 * Mstar / rp) * 0.97; // slight eccentricity

    return {
        bodies: [
            { x: -d, y: 0, vx: 0, vy: vb },   // Star A (downward = CCW screen)
            { x: d, y: 0, vx: 0, vy: -vb },   // Star B
            { x: 0, y: rp, vx: vp, vy: 0 },  // Planet (rightward = CCW screen)
        ],
        masses: [Mstar, Mstar, 25],
    };
};

/**
 * Chaotic starting configuration — chosen empirically for visual interest.
 */
const P_CHAOS = () => ({
    bodies: [
        { x: -140, y: -80, vx: 1.8, vy: 2.4 },
        { x: 150, y: 65, vx: -2.1, vy: -1.2 },
        { x: -15, y: 170, vx: 0.9, vy: -3.1 },
    ],
    masses: [155, 90, 125],
});

const PRESETS = {
    figure8: { label: 'Figure-8', make: P_FIGURE8 },
    lagrange: { label: 'Lagrange △', make: P_LAGRANGE },
    binary: { label: 'Binary+Planet', make: P_BINARY },
    chaos: { label: 'Chaotic', make: P_CHAOS },
};

// ─────────────────────────────────────────────────────────────────────
//  STATE
// ─────────────────────────────────────────────────────────────────────

const canvas = document.getElementById('c');
const ctx = canvas.getContext('2d');

let bodies = [];
let simTime = 0;
let running = false;
let activePreset = 'figure8';
let speedKey = 'normal';
let gravOn = true;

// Camera
let cam = { x: 0, y: 0, zoom: 1 };

// Drag state
let drag = { on: false, type: '', idx: -1, lx: 0, ly: 0 };

// Visualization flags
const viz = { force: false, vel: true, path: true, grid: false, com: false, energy: false };

// ─────────────────────────────────────────────────────────────────────
//  BODY CLASS
// ─────────────────────────────────────────────────────────────────────

class Body {
    constructor({ x, y, vx, vy, mass, color, name }) {
        this.x = x; this.y = y;
        this.vx = vx; this.vy = vy;
        this.ax = 0; this.ay = 0;
        this.mass = mass;
        this.color = color;
        this.name = name;
        this.alive = true;
        this.trail = [];
    }

    /** Visual radius based on mass (cube-root scaling = volume ∝ mass). */
    get radius() { return 4 + Math.cbrt(this.mass / BASE_MASS) * 13; }

    /** World → screen X/Y (via camera). */
    get sx() { return this.x * cam.zoom + canvas.width * 0.5 + cam.x; }
    get sy() { return this.y * cam.zoom + canvas.height * 0.5 + cam.y; }

    /** Append current position to trail if moved enough. */
    pushTrail() {
        const last = this.trail[this.trail.length - 1];
        if (!last || (this.x - last.x) ** 2 + (this.y - last.y) ** 2 > 0.4) {
            this.trail.push({ x: this.x, y: this.y });
            if (this.trail.length > TRAIL_MAX) this.trail.shift();
        }
    }

    clearTrail() { this.trail = []; }
}

// ─────────────────────────────────────────────────────────────────────
//  COORDINATE TRANSFORMS
// ─────────────────────────────────────────────────────────────────────

const w2s = (wx, wy) => ({
    x: wx * cam.zoom + canvas.width * 0.5 + cam.x,
    y: wy * cam.zoom + canvas.height * 0.5 + cam.y,
});

const s2w = (sx, sy) => ({
    x: (sx - canvas.width * 0.5 - cam.x) / cam.zoom,
    y: (sy - canvas.height * 0.5 - cam.y) / cam.zoom,
});

// ─────────────────────────────────────────────────────────────────────
//  PHYSICS ENGINE
// ─────────────────────────────────────────────────────────────────────

/**
 * Compute gravitational accelerations for all active bodies.
 *
 *  Newton's law of universal gravitation:
 *    F_ij = G · m_i · m_j / r_ij²                           (magnitude)
 *    â_ij = (r_j − r_i) / |r_j − r_i|                      (unit vector)
 *    a_i  += G · m_j · (r_j − r_i) / (r_ij² + ε²)^(3/2)   (softened)
 *
 *  Newton's 3rd law: we compute each pair (i<j) once, update both.
 *  This halves the O(n²) work.
 */
function computeAccels() {
    for (const b of bodies) { b.ax = 0; b.ay = 0; }
    if (!gravOn) return;

    const n = bodies.length;
    for (let i = 0; i < n - 1; i++) {
        if (!bodies[i].alive) continue;
        for (let j = i + 1; j < n; j++) {
            if (!bodies[j].alive) continue;
            const bi = bodies[i], bj = bodies[j];

            const dx = bj.x - bi.x;
            const dy = bj.y - bi.y;

            // Softened squared distance and its 3/2 power
            const r2 = dx * dx + dy * dy + SOFTENING_SQ;
            const r = Math.sqrt(r2);
            const r3 = r2 * r;                // r^3 = r · r²

            // Shared factor G/r³
            const gR3 = G / r3;

            // a_i += G·m_j·Δr / r³
            bi.ax += gR3 * bj.mass * dx;
            bi.ay += gR3 * bj.mass * dy;

            // a_j -= G·m_i·Δr / r³   (Newton's 3rd: opposite direction)
            bj.ax -= gR3 * bi.mass * dx;
            bj.ay -= gR3 * bi.mass * dy;
        }
    }
}

/**
 * Velocity-Verlet integration step (symplectic, 2nd-order).
 *
 * Algorithm:
 *   1.  x(t+dt) = x(t) + v(t)·dt + ½·a(t)·dt²    ← position update
 *   2.  a(t+dt) = force(x(t+dt)) / m               ← new accelerations
 *   3.  v(t+dt) = v(t) + ½·[a(t)+a(t+dt)]·dt      ← velocity update
 *
 * Velocity Verlet is symplectic: it conserves a modified energy
 * (shadow Hamiltonian), so long simulations don't gain or lose energy.
 *
 * @param {number} dt  Time step in τ.
 */
function verletStep(dt) {
    const n = bodies.length;
    // Save current accelerations; update positions (Step 1)
    const ax0 = new Float64Array(n);
    const ay0 = new Float64Array(n);
    for (let i = 0; i < n; i++) {
        const b = bodies[i];
        ax0[i] = b.ax; ay0[i] = b.ay;
        if (!b.alive) continue;
        b.x += b.vx * dt + 0.5 * b.ax * dt * dt;
        b.y += b.vy * dt + 0.5 * b.ay * dt * dt;
    }

    // Compute new accelerations (Step 2)
    computeAccels();

    // Update velocities with averaged acceleration (Step 3)
    for (let i = 0; i < n; i++) {
        const b = bodies[i];
        if (!b.alive) continue;
        b.vx += 0.5 * (ax0[i] + b.ax) * dt;
        b.vy += 0.5 * (ay0[i] + b.ay) * dt;
    }
}

/** Advance simulation by one animation frame (multiple sub-steps). */
function stepFrame() {
    const { substeps, dt } = SPEED[speedKey];
    for (let s = 0; s < substeps; s++) verletStep(dt);
    simTime += substeps * dt;
    if (viz.path) for (const b of bodies) if (b.alive) b.pushTrail();
}

// ─────────────────────────────────────────────────────────────────────
//  ENERGY & MOMENTUM
// ─────────────────────────────────────────────────────────────────────

function calcEnergy() {
    let ke = 0, pe = 0, px = 0, py = 0;
    for (const b of bodies) {
        if (!b.alive) continue;
        ke += 0.5 * b.mass * (b.vx * b.vx + b.vy * b.vy);
        px += b.mass * b.vx;
        py += b.mass * b.vy;
    }
    for (let i = 0; i < bodies.length; i++) {
        for (let j = i + 1; j < bodies.length; j++) {
            if (!bodies[i].alive || !bodies[j].alive) continue;
            const dx = bodies[j].x - bodies[i].x;
            const dy = bodies[j].y - bodies[i].y;
            pe -= G * bodies[i].mass * bodies[j].mass / Math.sqrt(dx * dx + dy * dy + SOFTENING_SQ);
        }
    }
    return { ke, pe, te: ke + pe, pm: Math.sqrt(px * px + py * py) };
}

// ─────────────────────────────────────────────────────────────────────
//  RENDERING
// ─────────────────────────────────────────────────────────────────────

/* Pre-generated static starfield */
const STARS = Array.from({ length: 260 }, () => ({
    fx: Math.random(), fy: Math.random(),
    r: Math.random() * 1.4 + 0.2,
    a: Math.random() * 0.65 + 0.07,
}));

function renderStarfield() {
    ctx.save();
    for (const s of STARS) {
        ctx.beginPath();
        ctx.arc(s.fx * canvas.width, s.fy * canvas.height, s.r, 0, Math.PI * 2);
        ctx.fillStyle = `rgba(255,255,255,${s.a})`;
        ctx.fill();
    }
    ctx.restore();
}

function renderGrid() {
    const sp = 100;  // world-unit spacing
    const tl = s2w(0, 0);
    const br = s2w(canvas.width, canvas.height);
    ctx.save();
    ctx.strokeStyle = 'rgba(255,255,255,0.05)';
    ctx.lineWidth = 1;
    for (let wx = Math.floor(tl.x / sp) * sp; wx <= br.x; wx += sp) {
        const sx = w2s(wx, 0).x;
        ctx.beginPath(); ctx.moveTo(sx, 0); ctx.lineTo(sx, canvas.height); ctx.stroke();
    }
    for (let wy = Math.floor(tl.y / sp) * sp; wy <= br.y; wy += sp) {
        const sy = w2s(0, wy).y;
        ctx.beginPath(); ctx.moveTo(0, sy); ctx.lineTo(canvas.width, sy); ctx.stroke();
    }
    // Origin axes (slightly brighter)
    const org = w2s(0, 0);
    ctx.strokeStyle = 'rgba(255,255,255,0.10)';
    ctx.beginPath(); ctx.moveTo(org.x, 0); ctx.lineTo(org.x, canvas.height); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(0, org.y); ctx.lineTo(canvas.width, org.y); ctx.stroke();
    ctx.restore();
}

/** Draw an arrow in screen-space from (x1,y1) to (x2,y2). */
function drawArrow(x1, y1, x2, y2, color, lw = 2, hd = 11) {
    const dx = x2 - x1, dy = y2 - y1, len = Math.hypot(dx, dy);
    if (len < 5) return;
    const ang = Math.atan2(dy, dx);
    const hl = Math.min(hd, len * 0.42);
    ctx.save();
    ctx.strokeStyle = ctx.fillStyle = color;
    ctx.lineWidth = lw;
    ctx.lineCap = 'round';
    // Shaft
    ctx.beginPath();
    ctx.moveTo(x1, y1);
    ctx.lineTo(x2 - hl * Math.cos(ang), y2 - hl * Math.sin(ang));
    ctx.stroke();
    // Head
    ctx.beginPath();
    ctx.moveTo(x2, y2);
    ctx.lineTo(x2 - hl * Math.cos(ang - 0.44), y2 - hl * Math.sin(ang - 0.44));
    ctx.lineTo(x2 - hl * Math.cos(ang + 0.44), y2 - hl * Math.sin(ang + 0.44));
    ctx.closePath(); ctx.fill();
    ctx.restore();
}

/** Render an orbital trail using gradient-fade band technique. */
function renderTrail(b) {
    const n = b.trail.length;
    if (n < 2) return;
    const BANDS = 10;
    ctx.save();
    ctx.lineJoin = ctx.lineCap = 'round';
    for (let band = 0; band < BANDS; band++) {
        const i0 = Math.floor(band / BANDS * n);
        const i1 = Math.floor((band + 1) / BANDS * n);
        if (i1 <= i0) continue;
        const α = (band + 0.5) / BANDS;
        const hx = Math.round(α * 0.78 * 255).toString(16).padStart(2, '0');
        ctx.strokeStyle = b.color + hx;
        ctx.lineWidth = 0.5 + α * 2.2;
        ctx.beginPath();
        const p0 = w2s(b.trail[i0].x, b.trail[i0].y);
        ctx.moveTo(p0.x, p0.y);
        for (let i = i0 + 1; i < i1; i++) {
            const p = w2s(b.trail[i].x, b.trail[i].y);
            ctx.lineTo(p.x, p.y);
        }
        ctx.stroke();
    }
    ctx.restore();
}

/** Render velocity arrow for a body. Tip is draggable when paused. */
function renderVelArrow(b) {
    const from = { x: b.sx, y: b.sy };
    const tip = w2s(b.x + b.vx * VEL_SCALE, b.y + b.vy * VEL_SCALE);
    drawArrow(from.x, from.y, tip.x, tip.y, '#33DD44', 2.5, 13);
    // Draggable handle at tip
    ctx.save();
    ctx.beginPath();
    ctx.arc(tip.x, tip.y, 6.5, 0, Math.PI * 2);
    ctx.fillStyle = '#33DD44';
    ctx.strokeStyle = '#fff';
    ctx.lineWidth = 1.5;
    ctx.fill(); ctx.stroke();
    ctx.restore();
}

/** Render gravitational-force arrow (proportional to net acceleration). */
function renderForceArrow(b) {
    const mag = Math.hypot(b.ax, b.ay);
    if (mag < 1e-9) return;
    const maxPx = 70;
    const sc = Math.min(maxPx, mag * 350 * cam.zoom) / mag;
    const s = { x: b.sx, y: b.sy };
    drawArrow(s.x, s.y, s.x + b.ax * sc, s.y + b.ay * sc, '#4477FF', 2, 10);
}

/** Render a body with glow effect. */
function renderBody(b) {
    const sx = b.sx, sy = b.sy;
    const r = b.radius * cam.zoom;
    const gr = r * 4;

    // Outer glow
    const glow = ctx.createRadialGradient(sx, sy, r * .25, sx, sy, gr);
    glow.addColorStop(0, b.color + 'cc');
    glow.addColorStop(0.5, b.color + '30');
    glow.addColorStop(1, b.color + '00');
    ctx.beginPath(); ctx.arc(sx, sy, gr, 0, Math.PI * 2);
    ctx.fillStyle = glow; ctx.fill();

    // Core sphere
    const grad = ctx.createRadialGradient(sx - r * .3, sy - r * .35, 0, sx, sy, r);
    grad.addColorStop(0, '#ffffff');
    grad.addColorStop(0.35, b.color);
    grad.addColorStop(1, b.color + 'bb');
    ctx.beginPath(); ctx.arc(sx, sy, r, 0, Math.PI * 2);
    ctx.fillStyle = grad; ctx.fill();

    // Label
    ctx.save();
    ctx.font = `bold ${Math.max(11, 10 + r * .12)}px system-ui,sans-serif`;
    ctx.fillStyle = b.color;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'bottom';
    ctx.shadowColor = '#000';
    ctx.shadowBlur = 5;
    ctx.fillText(b.name, sx, sy - r - 5);
    ctx.restore();
}

/** Render centre-of-mass crosshair. */
function renderCoM() {
    let mx = 0, my = 0, mt = 0;
    for (const b of bodies) {
        if (!b.alive) continue;
        mx += b.mass * b.x; my += b.mass * b.y; mt += b.mass;
    }
    if (!mt) return;
    const s = w2s(mx / mt, my / mt);
    const sz = 11;
    ctx.save();
    ctx.strokeStyle = '#ffdd55'; ctx.lineWidth = 1.5;
    ctx.setLineDash([3, 3]);
    ctx.beginPath(); ctx.moveTo(s.x - sz, s.y); ctx.lineTo(s.x + sz, s.y); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(s.x, s.y - sz); ctx.lineTo(s.x, s.y + sz); ctx.stroke();
    ctx.setLineDash([]);
    ctx.beginPath(); ctx.arc(s.x, s.y, 3.5, 0, Math.PI * 2);
    ctx.stroke();
    ctx.restore();
}

/** Master render call — invoked every animation frame. */
function render() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    renderStarfield();
    if (viz.grid) renderGrid();
    if (viz.path) for (const b of bodies) if (b.alive) renderTrail(b);
    if (viz.force) for (const b of bodies) if (b.alive) renderForceArrow(b);
    if (viz.vel) for (const b of bodies) if (b.alive) renderVelArrow(b);
    if (viz.com) renderCoM();
    for (const b of bodies) if (b.alive) renderBody(b);

    // HUD
    document.getElementById('tv').textContent =
        Math.floor(simTime * DAYS_PER_TAU).toLocaleString();

    if (viz.energy) {
        const E = calcEnergy();
        const fmt = v => {
            const a = Math.abs(v);
            if (a > 1e6) return (v / 1e6).toFixed(2) + 'M';
            if (a > 1e3) return (v / 1e3).toFixed(2) + 'K';
            return v.toFixed(1);
        };
        document.getElementById('eke').textContent = fmt(E.ke);
        document.getElementById('epe').textContent = fmt(E.pe);
        document.getElementById('ete').textContent = fmt(E.te);
        document.getElementById('emo').textContent = fmt(E.pm);
    }
}

// ─────────────────────────────────────────────────────────────────────
//  ANIMATION LOOP
// ─────────────────────────────────────────────────────────────────────

let lastT = 0;

function loop(t) {
    requestAnimationFrame(loop);
    if (t - lastT < 9) return;   // ≈ 111 fps cap (avoids physics runaway)
    lastT = t;
    if (running) stepFrame();
    render();
}

// ─────────────────────────────────────────────────────────────────────
//  PRESETS & RESET
// ─────────────────────────────────────────────────────────────────────

function loadPreset(key) {
    activePreset = key;
    simTime = 0;
    const { bodies: bds, masses } = PRESETS[key].make();

    bodies = bds.map((b, i) => new Body({
        x: b.x, y: b.y, vx: b.vx, vy: b.vy,
        mass: masses[i],
        color: COLS[i],
        name: NAMES[i],
    }));

    computeAccels();   // seed Verlet's stored acceleration
    syncMassUI();

    // Update active preset button
    document.querySelectorAll('.pb').forEach(el =>
        el.classList.toggle('active', el.dataset.p === key));

    // Sync body-toggle buttons
    document.querySelectorAll('.btog').forEach((el, i) => {
        el.classList.toggle('on', bodies[i] ? bodies[i].alive : false);
    });
}

function resetSim() {
    running = false;
    updatePlayBtn();
    loadPreset(activePreset);
}

// ─────────────────────────────────────────────────────────────────────
//  UI HELPERS
// ─────────────────────────────────────────────────────────────────────

function updatePlayBtn() {
    const btn = document.getElementById('bplay');
    btn.textContent = running ? '⏸' : '▶';
}

function syncMassUI() {
    bodies.forEach((b, i) => {
        const sl = document.getElementById(`ms${i}`);
        const mv = document.getElementById(`mv${i}`);
        if (sl) {
            sl.value = b.mass;
            mv.textContent = (b.mass / BASE_MASS).toFixed(1);
        }
    });
}

// ─────────────────────────────────────────────────────────────────────
//  INTERACTION
// ─────────────────────────────────────────────────────────────────────

function canvasXY(e) {
    const rect = canvas.getBoundingClientRect();
    const src = e.touches ? e.touches[0] : e;
    return {
        x: (src.clientX - rect.left) * (canvas.width / rect.width),
        y: (src.clientY - rect.top) * (canvas.height / rect.height),
    };
}

function hitBody(sx, sy) {
    for (let i = bodies.length - 1; i >= 0; i--) {
        const b = bodies[i];
        if (!b.alive) continue;
        if (Math.hypot(sx - b.sx, sy - b.sy) < Math.max(b.radius * cam.zoom + 12, 20))
            return i;
    }
    return -1;
}

function hitVelTip(sx, sy) {
    if (!viz.vel) return -1;
    for (let i = 0; i < bodies.length; i++) {
        const b = bodies[i];
        if (!b.alive) continue;
        const t = w2s(b.x + b.vx * VEL_SCALE, b.y + b.vy * VEL_SCALE);
        if (Math.hypot(sx - t.x, sy - t.y) < 16) return i;
    }
    return -1;
}

function onPointerDown(e) {
    if (e.button != null && e.button !== 0) return;
    const p = canvasXY(e);

    // Velocity tip — higher priority when paused
    if (!running) {
        const vi = hitVelTip(p.x, p.y);
        if (vi >= 0) {
            drag = { on: true, type: 'vel', idx: vi, lx: p.x, ly: p.y };
            canvas.style.cursor = 'crosshair';
            return;
        }
    }
    // Body
    const bi = hitBody(p.x, p.y);
    if (bi >= 0) {
        drag = { on: true, type: 'body', idx: bi, lx: p.x, ly: p.y };
        canvas.style.cursor = 'grabbing';
        return;
    }
    // Pan
    drag = { on: true, type: 'pan', idx: -1, lx: p.x, ly: p.y };
    canvas.style.cursor = 'grabbing';
}

function onPointerMove(e) {
    const p = canvasXY(e);

    if (!drag.on) {
        // Hover cursor
        if (!running && hitVelTip(p.x, p.y) >= 0) canvas.style.cursor = 'crosshair';
        else if (hitBody(p.x, p.y) >= 0) canvas.style.cursor = 'grab';
        else canvas.style.cursor = 'default';
        return;
    }

    const dx = p.x - drag.lx, dy = p.y - drag.ly;
    drag.lx = p.x; drag.ly = p.y;

    switch (drag.type) {
        case 'pan':
            cam.x += dx; cam.y += dy;
            break;
        case 'body': {
            const b = bodies[drag.idx];
            b.x += dx / cam.zoom; b.y += dy / cam.zoom;
            break;
        }
        case 'vel': {
            const b = bodies[drag.idx];
            const w = s2w(p.x, p.y);
            b.vx = (w.x - b.x) / VEL_SCALE;
            b.vy = (w.y - b.y) / VEL_SCALE;
            computeAccels();   // re-seed stored acceleration
            break;
        }
    }
}

function onPointerUp() {
    if (drag.on && drag.type !== 'pan') computeAccels();
    drag.on = false;
    canvas.style.cursor = 'default';
}

function onWheel(e) {
    e.preventDefault();
    const factor = e.deltaY > 0 ? 0.88 : 1.14;
    const p = canvasXY(e);
    const wBefore = s2w(p.x, p.y);
    cam.zoom = Math.max(0.07, Math.min(7, cam.zoom * factor));
    const wAfter = s2w(p.x, p.y);
    cam.x += (wAfter.x - wBefore.x) * cam.zoom;
    cam.y += (wAfter.y - wBefore.y) * cam.zoom;
    document.getElementById('z-sl').value = Math.round(cam.zoom * 100);
}

// ─────────────────────────────────────────────────────────────────────
//  KEYBOARD
// ─────────────────────────────────────────────────────────────────────

const KEY_MAP = {
    Space: () => { running = !running; updatePlayBtn(); },
    KeyR: () => resetSim(),
    KeyG: () => document.getElementById('ck-g').click(),
    KeyV: () => document.getElementById('ck-v').click(),
    KeyF: () => document.getElementById('ck-f').click(),
    KeyP: () => document.getElementById('ck-p').click(),
};

function onKey(e) {
    if (e.target.tagName === 'INPUT') return;
    if (KEY_MAP[e.code]) { e.preventDefault(); KEY_MAP[e.code](); }
}

// ─────────────────────────────────────────────────────────────────────
//  CANVAS RESIZE
// ─────────────────────────────────────────────────────────────────────

function resize() {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
}

// ─────────────────────────────────────────────────────────────────────
//  INIT
// ─────────────────────────────────────────────────────────────────────

function init() {
    resize();
    window.addEventListener('resize', resize);

    // Canvas events
    canvas.addEventListener('mousedown', onPointerDown);
    canvas.addEventListener('mousemove', onPointerMove);
    canvas.addEventListener('mouseup', onPointerUp);
    canvas.addEventListener('mouseleave', onPointerUp);
    canvas.addEventListener('wheel', onWheel, { passive: false });
    canvas.addEventListener('touchstart', e => { e.preventDefault(); onPointerDown(e); }, { passive: false });
    canvas.addEventListener('touchmove', e => { e.preventDefault(); onPointerMove(e); }, { passive: false });
    canvas.addEventListener('touchend', e => { e.preventDefault(); onPointerUp(); }, { passive: false });

    window.addEventListener('keydown', onKey);

    // ── Playback ──────────────────────────────────────────────────────
    document.getElementById('bplay').addEventListener('click', () => {
        running = !running; updatePlayBtn();
    });
    document.getElementById('breset').addEventListener('click', resetSim);
    document.getElementById('bstep').addEventListener('click', () => {
        if (!running) { stepFrame(); render(); }
    });

    // ── Speed ─────────────────────────────────────────────────────────
    document.querySelectorAll('input[name="spd"]').forEach(r =>
        r.addEventListener('change', e => { speedKey = e.target.value; }));

    // ── Gravity ───────────────────────────────────────────────────────
    document.querySelectorAll('input[name="grav"]').forEach(r =>
        r.addEventListener('change', e => {
            gravOn = e.target.value === 'on';
            if (gravOn) computeAccels();
            else bodies.forEach(b => { b.ax = 0; b.ay = 0; });
        }));

    // ── Visualization ─────────────────────────────────────────────────
    const vizMap = [
        ['ck-f', 'force'], ['ck-v', 'vel'], ['ck-p', 'path'],
        ['ck-g', 'grid'], ['ck-cm', 'com'], ['ck-e', 'energy'],
    ];
    vizMap.forEach(([id, key]) => {
        document.getElementById(id).addEventListener('change', e => {
            viz[key] = e.target.checked;
            if (key === 'path' && !viz.path) bodies.forEach(b => b.clearTrail());
            if (key === 'energy') document.getElementById('esec').hidden = !viz.energy;
        });
    });

    // ── Mass sliders ──────────────────────────────────────────────────
    for (let i = 0; i < 3; i++) {
        document.getElementById(`ms${i}`).addEventListener('input', e => {
            const v = +e.target.value;
            bodies[i].mass = v;
            document.getElementById(`mv${i}`).textContent = (v / BASE_MASS).toFixed(1);
            computeAccels();
        });
    }

    // ── Body toggles ──────────────────────────────────────────────────
    for (let i = 0; i < 3; i++) {
        document.getElementById(`tog${i}`).addEventListener('click', () => {
            bodies[i].alive = !bodies[i].alive;
            document.getElementById(`tog${i}`).classList.toggle('on', bodies[i].alive);
            bodies[i].clearTrail();
            computeAccels();
        });
    }

    // ── Presets ───────────────────────────────────────────────────────
    document.querySelectorAll('.pb').forEach(btn =>
        btn.addEventListener('click', () => {
            running = false; updatePlayBtn();
            loadPreset(btn.dataset.p);
        }));

    // ── Camera recenter ───────────────────────────────────────────────
    document.getElementById('btn-recenter').addEventListener('click', () => {
        cam = { x: 0, y: 0, zoom: 1 };
        document.getElementById('z-sl').value = 100;
    });

    // ── Zoom controls ─────────────────────────────────────────────────
    document.getElementById('z-in').addEventListener('click', () => {
        cam.zoom = Math.min(7, cam.zoom * 1.25);
        document.getElementById('z-sl').value = Math.round(cam.zoom * 100);
    });
    document.getElementById('z-out').addEventListener('click', () => {
        cam.zoom = Math.max(0.07, cam.zoom / 1.25);
        document.getElementById('z-sl').value = Math.round(cam.zoom * 100);
    });
    document.getElementById('z-sl').addEventListener('input', e => {
        cam.zoom = +e.target.value / 100;
    });

    // ── Hint fade ─────────────────────────────────────────────────────
    setTimeout(() => document.getElementById('hint').classList.add('gone'), 5500);

    // ── Boot ──────────────────────────────────────────────────────────
    loadPreset('figure8');
    requestAnimationFrame(loop);
}

init();